package programa2;

import java.awt.Dimension;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;

public class regPrograma2 extends javax.swing.JInternalFrame {

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;

    /**
     * Creates new form regPrograma2
     */
    public regPrograma2() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ocultarBarraTitulo();
        lblMensaje.setVisible(false);
        txtmsj.setVisible(false);
        txtAnio.setText("0");
        txtDia.setText("0");
        txtMes.setText("0");
    }

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    public void registrarPrograma() {

        try {
            String mes = txtMes.getText();
            String dia = txtDia.getText();
            String anio = txtAnio.getText();

            String fecha = "20" + anio + "-" + mes + "-" + dia;
            int validarAnio = Integer.parseInt(anio);
            if (validarAnio < 10) {
                fecha = "20" + "0" + anio + "-" + mes + "-" + dia;
            }
            if (anio.equals("00") | anio.equals("01") | anio.equals("02") | anio.equals("03") | anio.equals("04") | anio.equals("05") | anio.equals("06") | anio.equals("07") | anio.equals("08") | anio.equals("09")) {
                fecha = "20" + anio + "-" + mes + "-" + dia;
            }

            String TituloMensaje = txtTitulo.getText();
            String fechaDisco = fecha;

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_programas?useSSL=false", "root", "123456");
            CallableStatement stm = con.prepareCall("call sp_registroPrograma2(?,?)");

            stm.setString(1, TituloMensaje);
            stm.setString(2, fechaDisco);

            stm.execute();
        } catch (NumberFormatException | SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtMes = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        lblanio = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lbldia = new javax.swing.JLabel();
        lblmes1 = new javax.swing.JLabel();
        txtmsj = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Titulo del Mensaje:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 20));

        txtTitulo.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(102, 102, 102));
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitulo.setCaretColor(new java.awt.Color(51, 51, 51));
        txtTitulo.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 310, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha del Disco:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 130, 20));

        txtAnio.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        txtAnio.setForeground(new java.awt.Color(102, 102, 102));
        txtAnio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnio.setCaretColor(new java.awt.Color(51, 51, 51));
        txtAnio.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioKeyTyped(evt);
            }
        });
        jPanel1.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 50, 40));

        btnRegistrar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(102, 102, 102));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/checked.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 170, 50));

        btnCancelar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(102, 102, 102));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 170, 50));

        txtMes.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        txtMes.setForeground(new java.awt.Color(102, 102, 102));
        txtMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMes.setCaretColor(new java.awt.Color(51, 51, 51));
        txtMes.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 50, 40));

        txtDia.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        txtDia.setForeground(new java.awt.Color(102, 102, 102));
        txtDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDia.setCaretColor(new java.awt.Color(51, 51, 51));
        txtDia.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaKeyTyped(evt);
            }
        });
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 50, 40));

        lblanio.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        lblanio.setForeground(new java.awt.Color(102, 102, 102));
        lblanio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblanio.setText("Año");
        jPanel1.add(lblanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, 40, 20));

        lblMensaje.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 51, 51));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("mensaje");
        jPanel1.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 310, -1));

        lbldia.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        lbldia.setForeground(new java.awt.Color(102, 102, 102));
        lbldia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldia.setText("Día");
        jPanel1.add(lbldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 30, 20));

        lblmes1.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        lblmes1.setForeground(new java.awt.Color(102, 102, 102));
        lblmes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmes1.setText("Mes");
        jPanel1.add(lblmes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 40, 20));

        txtmsj.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txtmsj.setForeground(new java.awt.Color(255, 51, 51));
        txtmsj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtmsj.setText("msg");
        jPanel1.add(txtmsj, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 220, 290, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1040, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String titulo = txtTitulo.getText();
        String mes = txtMes.getText();
        String dia = txtDia.getText();
        String anio = txtAnio.getText();
        int validarDia = Integer.parseInt(dia);
        int validarMes = Integer.parseInt(mes);

        if (titulo.trim().equals("")) {
            lblMensaje.setText("LLENE LOS RECUADROS!");
            lblMensaje.setVisible(true);
            txtTitulo.requestFocus();
        } else if (mes.trim().equals("") || dia.trim().equals("") || anio.trim().equals("")) {
            txtmsj.setText("LLENE LOS RECUADROS!");
            txtmsj.setVisible(true);
        } else if (!numberValidator(mes.trim()) || !numberValidator(dia.trim()) || !numberValidator(anio.trim())) {
            txtmsj.setText("SOLO NUMEROS!");
            txtmsj.setVisible(true);
        } else if (validarDia > 31 || validarDia <= 0 || validarMes > 12 || validarMes <= 0) {
            txtmsj.setText("FORMATO DE FECHA INCORRECTO!");
            txtmsj.setVisible(true);
        } else {
            registrarPrograma();
            try {
                ListDataPrograma2 list = new ListDataPrograma2();
                MainPrograma2.dpView.add(list);
                list.toFront();
                list.setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(regPrograma2.class.getName()).log(Level.SEVERE, null, ex);
            }
            setActionsPrograma2 menu = new setActionsPrograma2();
            MainPrograma2.dpMenu.add(menu);
            menu.toFront();
            menu.setVisible(true);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        setActionsPrograma2 menu = new setActionsPrograma2();
        MainPrograma2.dpMenu.add(menu);
        menu.toFront();
        menu.setVisible(true);

        try {
            ListDataPrograma2 l = new ListDataPrograma2();
            MainPrograma2.dpView.add(l);
            l.toFront();
            l.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(setActionsPrograma2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
        String m = txtMes.getText();
        int limite = 2;
        if (m.length() == limite) {
            evt.consume();
            if (!numberValidator(m.trim())) {
                txtmsj.setText("SOLO NUMEROS!");
                txtmsj.setVisible(true);
            } else {
                txtDia.requestFocus();
            }
        }

    }//GEN-LAST:event_txtMesKeyTyped

    private void txtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyTyped
        String d = txtDia.getText();
        int limite = 2;
        if (d.length() == limite) {
            evt.consume();
            if (!numberValidator(d.trim())) {
                txtmsj.setText("SOLO NUMEROS!");
                txtmsj.setVisible(true);
            } else {
                txtAnio.requestFocus();
            }
        }
    }//GEN-LAST:event_txtDiaKeyTyped

    private void txtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioKeyTyped
        String a = txtAnio.getText();
        int limite = 2;
        if (a.length() == limite) {
            evt.consume();
            if (!numberValidator(a.trim())) {
                txtmsj.setText("SOLO NUMEROS!");
                txtmsj.setVisible(true);
            } else {
                btnRegistrar.requestFocus();
            }
        }
    }//GEN-LAST:event_txtAnioKeyTyped

    private boolean numberValidator(String data) {
        return data.matches("[0-9]*");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblanio;
    private javax.swing.JLabel lbldia;
    private javax.swing.JLabel lblmes1;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JLabel txtmsj;
    // End of variables declaration//GEN-END:variables

}
