/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa2;

import Conexion.Conexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static programa2.ListDataPrograma2.TablaPrograma2;

/**
 *
 * @author Aless
 */
public class updateRegPrograma2 extends javax.swing.JInternalFrame {

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;

    private PreparedStatement pstm;

    /**
     * Creates new form updateRegEPDO
     */
    public updateRegPrograma2() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ocultarBarraTitulo();
        lblMensaje.setVisible(false);
        lblMsj2.setVisible(false);
        setValuesToEdit();
    }

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    public void focusNewRow() {
        TablaPrograma2.getSelectionModel().setSelectionInterval(0, 0);
    }

    public void focusRowEdited(int fila) {
        TablaPrograma2.getSelectionModel().setSelectionInterval(fila, fila);
    }

    public void goToMenu() {
        setActionsPrograma2 menu = new setActionsPrograma2();
        MainPrograma2.dpMenu.add(menu);
        menu.toFront();
        menu.setVisible(true);
    }

    public void setValuesToEdit() {
        DefaultTableModel modelo = (DefaultTableModel) TablaPrograma2.getModel();
        String tituloMensaje = String.valueOf(modelo.getValueAt(TablaPrograma2.getSelectedRow(), 2));
        String fecha = String.valueOf(modelo.getValueAt(TablaPrograma2.getSelectedRow(), 3));
        String mes = fecha.substring(0, 2);
        String dia = fecha.substring(3, 5);
        String anio = fecha.substring(8, 10);

        if (tituloMensaje.equals("-- SIN REGISTRAR!! --")) {
            txtTitulo.setText("");
            txtDia.setText("0");
            txtMes.setText("0");
            txtAnio.setText("0");
        } else {
            txtTitulo.setText(tituloMensaje);
            txtDia.setText(dia);
            txtMes.setText(mes);
            txtAnio.setText(anio);
        }
    }

    public void getData() throws ClassNotFoundException, SQLException {
        Conexion con = new Conexion("localhost", "root", "123456", "gestion_programas");
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rs = con.ejecutarSelect("select * from view_registroPrograma2");
        ResultSetMetaData md = rs.getMetaData();

        int columnas = md.getColumnCount();
        for (int i = 1; i <= columnas; i++) {
            modelo.addColumn(md.getColumnLabel(i));
        }

        while (rs.next()) {
            Object[] fila = new Object[columnas];
            for (int i = 0; i < columnas; i++) {
                fila[i] = rs.getObject(i + 1);
            }
            modelo.addRow(fila);
            fila = null;
        }
        TablaPrograma2.setModel(modelo);
        con.desconectar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        lblanio = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lbldia = new javax.swing.JLabel();
        lblmes = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblMsj2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Titulo del Mensaje:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 20));

        txtTitulo.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(102, 102, 102));
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitulo.setCaretColor(new java.awt.Color(51, 51, 51));
        txtTitulo.setSelectedTextColor(null);
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 310, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha del Disco:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 130, 20));

        txtAnio.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        txtAnio.setForeground(new java.awt.Color(102, 102, 102));
        txtAnio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnio.setSelectedTextColor(null);
        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioKeyTyped(evt);
            }
        });
        jPanel1.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 50, 40));

        txtMes.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        txtMes.setForeground(new java.awt.Color(102, 102, 102));
        txtMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMes.setSelectedTextColor(null);
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 50, 40));

        txtDia.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        txtDia.setForeground(new java.awt.Color(102, 102, 102));
        txtDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDia.setSelectedTextColor(null);
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaKeyTyped(evt);
            }
        });
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 50, 40));

        lblanio.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        lblanio.setForeground(new java.awt.Color(102, 102, 102));
        lblanio.setText("Año");
        jPanel1.add(lblanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, 40, 20));

        lblMensaje.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 51, 51));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("mensaje");
        jPanel1.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 310, -1));

        lbldia.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        lbldia.setForeground(new java.awt.Color(102, 102, 102));
        lbldia.setText("Día");
        jPanel1.add(lbldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 30, 20));

        lblmes.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        lblmes.setForeground(new java.awt.Color(102, 102, 102));
        lblmes.setText("Mes");
        jPanel1.add(lblmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 40, 20));

        btnUpdate.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(102, 102, 102));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/checkmark.png"))); // NOI18N
        btnUpdate.setText("ACTUALIZAR");
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setIconTextGap(0);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 170, 50));

        btnCancel.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(102, 102, 102));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        btnCancel.setText("CANCELAR");
        btnCancel.setContentAreaFilled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 170, 50));

        lblMsj2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblMsj2.setForeground(new java.awt.Color(255, 51, 51));
        lblMsj2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMsj2.setText("msg");
        jPanel1.add(lblMsj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1040, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioKeyTyped
        String a = txtAnio.getText();
        int limite = 2;
        if (a.length() == limite) {
            evt.consume();
            if (!numberValidator(a.trim())) {
                lblMsj2.setText("SOLO NUMEROS!");
                lblMsj2.setVisible(true);
            }
        }
    }//GEN-LAST:event_txtAnioKeyTyped

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
        String m = txtMes.getText();
        int limite = 2;
        if (m.length() == limite) {
            evt.consume();
            if (!numberValidator(m.trim())) {
                lblMsj2.setText("SOLO NUMEROS!");
                lblMsj2.setVisible(true);
            } else {
                txtDia.requestFocus();
            }
        }
    }//GEN-LAST:event_txtMesKeyTyped

    private void txtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyTyped

        String d = txtDia.getText();
        int limite = 2;
        if (d.length() == limite) {
            evt.consume();
            if (!numberValidator(d.trim())) {
                lblMsj2.setText("SOLO NUMEROS!");
                lblMsj2.setVisible(true);
            } else {
                txtAnio.requestFocus();
            }
        }
    }//GEN-LAST:event_txtDiaKeyTyped

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        setActionsPrograma2 menu = new setActionsPrograma2();
        MainPrograma2.dpMenu.add(menu);
        menu.toFront();
        menu.setVisible(true);
        ListDataPrograma2.btnEditList.setEnabled(true);
        ListDataPrograma2.txtBuscar.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) TablaPrograma2.getModel();

        String id = String.valueOf(modelo.getValueAt(TablaPrograma2.getSelectedRow(), 0));
        String tituloMensaje = txtTitulo.getText();
        int id_fila = Integer.parseInt(id);
        String mes = txtMes.getText();
        String dia = txtDia.getText();
        String anio = txtAnio.getText();
        String fecha_disco = "20" + anio + "-" + mes + "-" + dia;
        int validarAnio = Integer.parseInt(anio);
        int validarDia = Integer.parseInt(dia);
        int validarMes = Integer.parseInt(mes);

        if (validarAnio < 10) {
            fecha_disco = "20" + "0" + anio + "-" + mes + "-" + dia;
        }

        if (anio.equals("00") | anio.equals("01") | anio.equals("02") | anio.equals("03") | anio.equals("04") | anio.equals("05") | anio.equals("06") | anio.equals("07") | anio.equals("08") | anio.equals("09")) {
            fecha_disco = "20" + anio + "-" + mes + "-" + dia;
        }
        int fila = TablaPrograma2.getSelectedRow();

        if (tituloMensaje.trim().equals("")) {
            lblMensaje.setVisible(true);
            lblMensaje.setText("LLENE LOS RECUADROS!");
            txtTitulo.requestFocus();
        } else if (mes.trim().equals("") || dia.trim().equals("") || anio.trim().equals("")) {
            lblMsj2.setVisible(true);
            lblMsj2.setText("LLENE LOS RECUADROS!");
        } else if (!numberValidator(mes.trim()) || !numberValidator(dia.trim()) || !numberValidator(anio.trim())) {
            lblMsj2.setText("SOLO NUMEROS!");
            lblMsj2.setVisible(true);
        } else if (validarDia>31 || validarDia<=0 || validarMes>12 || validarMes<=0) {
            lblMsj2.setText("FORMATO DE FECHA INCORRECTO!");
            lblMsj2.setVisible(true);
        } else {
            try {
                String sql = "update registro_Programa2 set titulo_mensaje=?,fecha_emision=? where id=" + id_fila + ";";
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_programas?useSSL=false", "root", "123456");

                pstm = con.prepareStatement(sql);
                pstm.setString(1, tituloMensaje);
                pstm.setString(2, fecha_disco);
                pstm.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registro modificado!");
                getData();
                goToMenu();
                focusRowEdited(fila);
                customTablePrograma2();
                ListDataPrograma2.btnEditList.setEnabled(true);
                ListDataPrograma2.txtBuscar.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(ListDataPrograma2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(updateRegPrograma2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    public void customTablePrograma2() {
        
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(23, 32, 42));
        headerRenderer.setForeground(Color.WHITE);
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        headerRenderer.setPreferredSize(new java.awt.Dimension(0, 50));

        for (int i = 0; i < TablaPrograma2.getModel().getColumnCount(); i++) {
            TablaPrograma2.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        TablaPrograma2.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        TablaPrograma2.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        TablaPrograma2.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        TablaPrograma2.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        TablaPrograma2.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);

        TablaPrograma2.setSelectionBackground(new Color(46, 204, 113));
        TablaPrograma2.setSelectionForeground(new Color(23, 32, 42));
        TablaPrograma2.setBackground(new Color(248, 249, 249));
        TablaPrograma2.setForeground(Color.darkGray);
        TablaPrograma2.setFont(new java.awt.Font("Tw Cen MT", 0, 17));
        TablaPrograma2.setDefaultEditor(Object.class, null);

        TablaPrograma2.getTableHeader().setReorderingAllowed(false);
        TablaPrograma2.setRowHeight(38);
        TablaPrograma2.setGridColor(new java.awt.Color(0, 0, 0));

        TablaPrograma2.getColumnModel().getColumn(0).setPreferredWidth(0);
        TablaPrograma2.getColumnModel().getColumn(1).setPreferredWidth(400);
        TablaPrograma2.getColumnModel().getColumn(2).setPreferredWidth(300);
        TablaPrograma2.getColumnModel().getColumn(3).setPreferredWidth(215);
        TablaPrograma2.getColumnModel().getColumn(4).setPreferredWidth(350);

        TablaPrograma2.getColumnModel().getColumn(0).setMaxWidth(0);
        TablaPrograma2.getColumnModel().getColumn(0).setMinWidth(0);
        TablaPrograma2.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        TablaPrograma2.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

    }

    private boolean numberValidator(String data) {
        return data.matches("[0-9]*");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMsj2;
    private javax.swing.JLabel lblanio;
    private javax.swing.JLabel lbldia;
    private javax.swing.JLabel lblmes;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
