package Frames;

import Conexion.Preferencias;
import Home.Normas;
import Home.ReportarProblemas;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import main.singleInstance;

/**
 *
 * @author Aless
 */
public class Home extends javax.swing.JInternalFrame {

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;

    public Home() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ocultarBarraTitulo();
    }

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    public void restartApp() {
        String path = new File(".").getAbsolutePath();
        System.out.println(path);
        new singleInstance().cerrarApp();

        try {
            new ProcessBuilder("cmd", "/c start /min " + path + "\\dist\\control_programas.jar ^& exit").start();
        } catch (IOException ex) {
            Logger.getLogger(Normas.class.getName()).log(Level.SEVERE, null, ex);
        }
        new singleInstance().cerrarApp();
        System.exit(0);
    }

    public String fileSelect() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Seleccionar Carpeta del Programa");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
//        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
        } else {
            System.out.println("No Selection ");
        }

        File dir = chooser.getSelectedFile();
        return dir.toString();
    }

    public String folderSelect() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Seleccionar Carpeta del Programa");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
        } else {
            System.out.println("No Selection ");
        }

        File dir = chooser.getSelectedFile();
        return dir.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnNormas = new javax.swing.JButton();
        btnHorarios = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE ADMINISTRACION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 650, 191));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/automatizacion.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 230, 190));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 830, 10));

        btnNormas.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        btnNormas.setForeground(new java.awt.Color(102, 102, 102));
        btnNormas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/normas.png"))); // NOI18N
        btnNormas.setText("NORMAS");
        btnNormas.setContentAreaFilled(false);
        btnNormas.setFocusPainted(false);
        btnNormas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNormas.setIconTextGap(10);
        btnNormas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNormas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormasActionPerformed(evt);
            }
        });
        jPanel2.add(btnNormas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        btnHorarios.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        btnHorarios.setForeground(new java.awt.Color(102, 102, 102));
        btnHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar2.png"))); // NOI18N
        btnHorarios.setText("HORARIOS");
        btnHorarios.setContentAreaFilled(false);
        btnHorarios.setFocusPainted(false);
        btnHorarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHorarios.setIconTextGap(10);
        btnHorarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        btnReport.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        btnReport.setForeground(new java.awt.Color(102, 102, 102));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/failure.png"))); // NOI18N
        btnReport.setText("REPORTAR PROBLEMAS");
        btnReport.setContentAreaFilled(false);
        btnReport.setFocusPainted(false);
        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReport.setIconTextGap(10);
        btnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jPanel2.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        btnNotas.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        btnNotas.setForeground(new java.awt.Color(102, 102, 102));
        btnNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notes.png"))); // NOI18N
        btnNotas.setText("NOTAS");
        btnNotas.setContentAreaFilled(false);
        btnNotas.setFocusPainted(false);
        btnNotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotas.setIconTextGap(10);
        btnNotas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        jPanel2.add(btnNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1040, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormasActionPerformed
        try {
            Normas n = new Normas();
            Principal.dpHome.add(n);
            n.toFront();
            n.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNormasActionPerformed

    private void btnHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorariosActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirHorarios));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }
            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Archivo no encontrado. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = fileSelect();
                Preferencias.dirHorarios = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnHorariosActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        ReportarProblemas rp = new ReportarProblemas();
        Principal.dpHome.add(rp);
        rp.toFront();
        rp.setVisible(true);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirNotas));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }
            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirNotas = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnNotasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHorarios;
    private javax.swing.JButton btnNormas;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
