package Frames;

import Conexion.Preferencias;
import Home.Normas;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import main.singleInstance;

/**
 *
 * @author Aless
 */
public class Programas extends javax.swing.JInternalFrame {

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;

    /**
     * Creates new form Programas
     */
    public Programas() {
        initComponents();
        ocultarBarraTitulo();
        ocultarBotones();
    }

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));//bordes
    }

    public void ocultarBotones() {
        btnFolderEALAF.setVisible(false);
        btnWebEALAF.setVisible(false);
        btnFolderComent.setVisible(false);
        btnWebComent.setVisible(false);
        btnFolderConciencia.setVisible(false);
        btnWebConciencia.setVisible(false);
        btnFolderTTB.setVisible(false);
        btnWebTTB.setVisible(false);
        btnFolderLPDDPH.setVisible(false);
        btnWebLPDDPH.setVisible(false);
        btnFolderEC.setVisible(false);
        btnWebEC.setVisible(false);
        btnFolderResp.setVisible(false);
        btnWebResp.setVisible(false);
        btnFolderCruzada.setVisible(false);
        btnWebCruzada.setVisible(false);
        btnFolderLFVPO.setVisible(false);
    }

    public void restartApp() {
        String path = new File(".").getAbsolutePath();
        System.out.println(path);
        new singleInstance().cerrarApp();

        try {
            new ProcessBuilder("cmd", "/c start /min " + path + "\\control_programas.jar ^& exit").start();
        } catch (IOException ex) {
            Logger.getLogger(Normas.class.getName()).log(Level.SEVERE, null, ex);
        }
        new singleInstance().cerrarApp();
        System.exit(0);
    }

    public String folderSelect() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Seleccionar Carpeta del Programa");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
        } else {
            System.out.println("No Selection ");
        }

        File dir = chooser.getSelectedFile();
        return dir.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEALAF = new javax.swing.JButton();
        btnConciencia = new javax.swing.JButton();
        btnEC = new javax.swing.JButton();
        btnLPDDPH = new javax.swing.JButton();
        btnResp = new javax.swing.JButton();
        btnLFVPO = new javax.swing.JButton();
        btnCruzada = new javax.swing.JButton();
        btnTTB = new javax.swing.JButton();
        btnComent = new javax.swing.JButton();
        btnFolderLFVPO = new javax.swing.JButton();
        btnFolderResp = new javax.swing.JButton();
        btnWebResp = new javax.swing.JButton();
        btnFolderCruzada = new javax.swing.JButton();
        btnWebCruzada = new javax.swing.JButton();
        btnFolderLPDDPH = new javax.swing.JButton();
        btnWebLPDDPH = new javax.swing.JButton();
        btnFolderEC = new javax.swing.JButton();
        btnWebEC = new javax.swing.JButton();
        btnFolderTTB = new javax.swing.JButton();
        btnWebTTB = new javax.swing.JButton();
        btnFolderConciencia = new javax.swing.JButton();
        btnWebConciencia = new javax.swing.JButton();
        btnFolderEALAF = new javax.swing.JButton();
        btnWebEALAF = new javax.swing.JButton();
        btnWebComent = new javax.swing.JButton();
        btnFolderComent = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEALAF.setBackground(new java.awt.Color(255, 255, 255));
        btnEALAF.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        btnEALAF.setForeground(new java.awt.Color(102, 102, 102));
        btnEALAF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ealaf.png"))); // NOI18N
        btnEALAF.setText("ENFOQUE A LA FAMILIA");
        btnEALAF.setBorder(null);
        btnEALAF.setContentAreaFilled(false);
        btnEALAF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEALAF.setIconTextGap(20);
        btnEALAF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEALAF.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEALAFMouseMoved(evt);
            }
        });
        btnEALAF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEALAFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEALAFMousePressed(evt);
            }
        });
        jPanel1.add(btnEALAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 180, 160));

        btnConciencia.setBackground(new java.awt.Color(255, 255, 255));
        btnConciencia.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        btnConciencia.setForeground(new java.awt.Color(102, 102, 102));
        btnConciencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/conciencia.png"))); // NOI18N
        btnConciencia.setText("UN MENSAJE A LA CONCIENCIA");
        btnConciencia.setBorder(null);
        btnConciencia.setContentAreaFilled(false);
        btnConciencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConciencia.setIconTextGap(15);
        btnConciencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConciencia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnConcienciaMouseMoved(evt);
            }
        });
        btnConciencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConcienciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConcienciaMousePressed(evt);
            }
        });
        jPanel1.add(btnConciencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 240, 160));

        btnEC.setBackground(new java.awt.Color(255, 255, 255));
        btnEC.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        btnEC.setForeground(new java.awt.Color(102, 102, 102));
        btnEC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contacto.png"))); // NOI18N
        btnEC.setText("EN CONTACTO");
        btnEC.setBorder(null);
        btnEC.setContentAreaFilled(false);
        btnEC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEC.setIconTextGap(20);
        btnEC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEC.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnECMouseMoved(evt);
            }
        });
        btnEC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnECMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnECMousePressed(evt);
            }
        });
        jPanel1.add(btnEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 190, 160));

        btnLPDDPH.setBackground(new java.awt.Color(255, 255, 255));
        btnLPDDPH.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        btnLPDDPH.setForeground(new java.awt.Color(102, 102, 102));
        btnLPDDPH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lpddh.png"))); // NOI18N
        btnLPDDPH.setText("LA PALABRA DE DIOS PARA HOY");
        btnLPDDPH.setBorder(null);
        btnLPDDPH.setContentAreaFilled(false);
        btnLPDDPH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLPDDPH.setIconTextGap(25);
        btnLPDDPH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLPDDPH.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLPDDPHMouseMoved(evt);
            }
        });
        btnLPDDPH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLPDDPHMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLPDDPHMousePressed(evt);
            }
        });
        jPanel1.add(btnLPDDPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 250, 170));

        btnResp.setBackground(new java.awt.Color(255, 255, 255));
        btnResp.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        btnResp.setForeground(new java.awt.Color(102, 102, 102));
        btnResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/responde.png"))); // NOI18N
        btnResp.setText("LUIS PALAU RESPONDE");
        btnResp.setBorder(null);
        btnResp.setContentAreaFilled(false);
        btnResp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResp.setIconTextGap(20);
        btnResp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRespMouseMoved(evt);
            }
        });
        btnResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRespMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRespMousePressed(evt);
            }
        });
        jPanel1.add(btnResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 190, 160));

        btnLFVPO.setBackground(new java.awt.Color(255, 255, 255));
        btnLFVPO.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        btnLFVPO.setForeground(new java.awt.Color(102, 102, 102));
        btnLFVPO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lfvpo.png"))); // NOI18N
        btnLFVPO.setText("LA FÉ VIENE POR EL OÍR");
        btnLFVPO.setBorder(null);
        btnLFVPO.setContentAreaFilled(false);
        btnLFVPO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLFVPO.setIconTextGap(20);
        btnLFVPO.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLFVPO.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLFVPOMouseMoved(evt);
            }
        });
        btnLFVPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLFVPOMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLFVPOMousePressed(evt);
            }
        });
        jPanel1.add(btnLFVPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 190, 170));

        btnCruzada.setBackground(new java.awt.Color(255, 255, 255));
        btnCruzada.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        btnCruzada.setForeground(new java.awt.Color(102, 102, 102));
        btnCruzada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cruzada.png"))); // NOI18N
        btnCruzada.setText("CRUZADA CON LUIS PALAU");
        btnCruzada.setBorder(null);
        btnCruzada.setContentAreaFilled(false);
        btnCruzada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCruzada.setIconTextGap(20);
        btnCruzada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCruzada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCruzadaMouseMoved(evt);
            }
        });
        btnCruzada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCruzadaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCruzadaMousePressed(evt);
            }
        });
        jPanel1.add(btnCruzada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 160));

        btnTTB.setBackground(new java.awt.Color(255, 255, 255));
        btnTTB.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        btnTTB.setForeground(new java.awt.Color(102, 102, 102));
        btnTTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ttb.png"))); // NOI18N
        btnTTB.setText("A TRAVÉS DE LA BIBLIA");
        btnTTB.setBorder(null);
        btnTTB.setContentAreaFilled(false);
        btnTTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTTB.setIconTextGap(30);
        btnTTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTTB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTTBMouseMoved(evt);
            }
        });
        btnTTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTTBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTTBMousePressed(evt);
            }
        });
        jPanel1.add(btnTTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 180, 170));

        btnComent.setBackground(new java.awt.Color(255, 255, 255));
        btnComent.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        btnComent.setForeground(new java.awt.Color(102, 102, 102));
        btnComent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comentario.png"))); // NOI18N
        btnComent.setText("COMENTARIO ENFOQUE");
        btnComent.setBorder(null);
        btnComent.setContentAreaFilled(false);
        btnComent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComent.setIconTextGap(28);
        btnComent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnComentMouseMoved(evt);
            }
        });
        btnComent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnComentMousePressed(evt);
            }
        });
        jPanel1.add(btnComent, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 190, 160));

        btnFolderLFVPO.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnFolderLFVPO.setForeground(new java.awt.Color(102, 102, 102));
        btnFolderLFVPO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N
        btnFolderLFVPO.setText("Buscar en carpeta");
        btnFolderLFVPO.setBorder(null);
        btnFolderLFVPO.setContentAreaFilled(false);
        btnFolderLFVPO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolderLFVPO.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolderLFVPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderLFVPOActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolderLFVPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, -1, -1));

        btnFolderResp.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnFolderResp.setForeground(new java.awt.Color(102, 102, 102));
        btnFolderResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N
        btnFolderResp.setText("Buscar en carpeta");
        btnFolderResp.setBorder(null);
        btnFolderResp.setContentAreaFilled(false);
        btnFolderResp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolderResp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolderResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderRespActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolderResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        btnWebResp.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnWebResp.setForeground(new java.awt.Color(102, 102, 102));
        btnWebResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnWebResp.setText("Ir al siio web");
        btnWebResp.setBorder(null);
        btnWebResp.setContentAreaFilled(false);
        btnWebResp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWebResp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWebResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebRespActionPerformed(evt);
            }
        });
        jPanel1.add(btnWebResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        btnFolderCruzada.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnFolderCruzada.setForeground(new java.awt.Color(102, 102, 102));
        btnFolderCruzada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N
        btnFolderCruzada.setText("Buscar en carpeta");
        btnFolderCruzada.setBorder(null);
        btnFolderCruzada.setContentAreaFilled(false);
        btnFolderCruzada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolderCruzada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolderCruzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderCruzadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolderCruzada, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        btnWebCruzada.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnWebCruzada.setForeground(new java.awt.Color(102, 102, 102));
        btnWebCruzada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnWebCruzada.setText("Ir al sitio web");
        btnWebCruzada.setBorder(null);
        btnWebCruzada.setContentAreaFilled(false);
        btnWebCruzada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWebCruzada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWebCruzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebCruzadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnWebCruzada, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        btnFolderLPDDPH.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnFolderLPDDPH.setForeground(new java.awt.Color(102, 102, 102));
        btnFolderLPDDPH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N
        btnFolderLPDDPH.setText("Buscar en carpeta");
        btnFolderLPDDPH.setBorder(null);
        btnFolderLPDDPH.setContentAreaFilled(false);
        btnFolderLPDDPH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolderLPDDPH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolderLPDDPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderLPDDPHActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolderLPDDPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, -1, -1));

        btnWebLPDDPH.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnWebLPDDPH.setForeground(new java.awt.Color(102, 102, 102));
        btnWebLPDDPH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnWebLPDDPH.setText("Ir al sitio web");
        btnWebLPDDPH.setBorder(null);
        btnWebLPDDPH.setContentAreaFilled(false);
        btnWebLPDDPH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWebLPDDPH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWebLPDDPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebLPDDPHActionPerformed(evt);
            }
        });
        jPanel1.add(btnWebLPDDPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        btnFolderEC.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnFolderEC.setForeground(new java.awt.Color(102, 102, 102));
        btnFolderEC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N
        btnFolderEC.setText("Buscar en carpeta");
        btnFolderEC.setBorder(null);
        btnFolderEC.setContentAreaFilled(false);
        btnFolderEC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolderEC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolderEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderECActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolderEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, -1, -1));

        btnWebEC.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnWebEC.setForeground(new java.awt.Color(102, 102, 102));
        btnWebEC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnWebEC.setText("Ir al sitio web");
        btnWebEC.setBorder(null);
        btnWebEC.setContentAreaFilled(false);
        btnWebEC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWebEC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWebEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebECActionPerformed(evt);
            }
        });
        jPanel1.add(btnWebEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, -1, -1));

        btnFolderTTB.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnFolderTTB.setForeground(new java.awt.Color(102, 102, 102));
        btnFolderTTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N
        btnFolderTTB.setText("Buscar en carpeta");
        btnFolderTTB.setBorder(null);
        btnFolderTTB.setContentAreaFilled(false);
        btnFolderTTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolderTTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolderTTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderTTBActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolderTTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, -1, -1));

        btnWebTTB.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnWebTTB.setForeground(new java.awt.Color(102, 102, 102));
        btnWebTTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnWebTTB.setText("Ir al sitio web");
        btnWebTTB.setBorder(null);
        btnWebTTB.setContentAreaFilled(false);
        btnWebTTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWebTTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWebTTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebTTBActionPerformed(evt);
            }
        });
        jPanel1.add(btnWebTTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        btnFolderConciencia.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnFolderConciencia.setForeground(new java.awt.Color(102, 102, 102));
        btnFolderConciencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N
        btnFolderConciencia.setText("Buscar en carpeta");
        btnFolderConciencia.setBorder(null);
        btnFolderConciencia.setContentAreaFilled(false);
        btnFolderConciencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolderConciencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolderConciencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderConcienciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolderConciencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        btnWebConciencia.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnWebConciencia.setForeground(new java.awt.Color(102, 102, 102));
        btnWebConciencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnWebConciencia.setText("Ir al sitio web");
        btnWebConciencia.setBorder(null);
        btnWebConciencia.setContentAreaFilled(false);
        btnWebConciencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWebConciencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWebConciencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebConcienciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnWebConciencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        btnFolderEALAF.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnFolderEALAF.setForeground(new java.awt.Color(102, 102, 102));
        btnFolderEALAF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N
        btnFolderEALAF.setText("Buscar en carpeta");
        btnFolderEALAF.setBorder(null);
        btnFolderEALAF.setContentAreaFilled(false);
        btnFolderEALAF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolderEALAF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolderEALAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderEALAFActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolderEALAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        btnWebEALAF.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnWebEALAF.setForeground(new java.awt.Color(102, 102, 102));
        btnWebEALAF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnWebEALAF.setText("Ir al sitio web");
        btnWebEALAF.setBorder(null);
        btnWebEALAF.setContentAreaFilled(false);
        btnWebEALAF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWebEALAF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWebEALAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebEALAFActionPerformed(evt);
            }
        });
        jPanel1.add(btnWebEALAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        btnWebComent.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnWebComent.setForeground(new java.awt.Color(102, 102, 102));
        btnWebComent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnWebComent.setText("Ir al sitio web");
        btnWebComent.setBorder(null);
        btnWebComent.setContentAreaFilled(false);
        btnWebComent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWebComent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWebComent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebComentActionPerformed(evt);
            }
        });
        jPanel1.add(btnWebComent, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, -1, -1));

        btnFolderComent.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnFolderComent.setForeground(new java.awt.Color(102, 102, 102));
        btnFolderComent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N
        btnFolderComent.setText("Buscar en Carpeta");
        btnFolderComent.setBorder(null);
        btnFolderComent.setContentAreaFilled(false);
        btnFolderComent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolderComent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolderComent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderComentActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolderComent, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1040, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFolderLFVPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderLFVPOActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirLFVPO));
        } catch (Exception ex) {
            System.out.println(ex);

            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta de programa no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirLFVPO = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnFolderLFVPOActionPerformed

    private void btnFolderRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderRespActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirResponde));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }

            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta de programa no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirResponde = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnFolderRespActionPerformed

    private void btnWebRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebRespActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("http://luispalau.net/v2/programas-radio-responde_baja.aspx"));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "No se puede acceder al sitio web");
        }
    }//GEN-LAST:event_btnWebRespActionPerformed

    private void btnFolderCruzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderCruzadaActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirCruzada));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }

            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta de programa no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirCruzada = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnFolderCruzadaActionPerformed

    private void btnWebCruzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebCruzadaActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("http://luispalau.net/v2/programas-radio-cruzada_baja.aspx"));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "No se puede acceder al sitio web");
        }
    }//GEN-LAST:event_btnWebCruzadaActionPerformed

    private void btnFolderLPDDPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderLPDDPHActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirLPDDPH));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }

            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta de programa no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirLPDDPH = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnFolderLPDDPHActionPerformed

    private void btnWebLPDDPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebLPDDPHActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.twr360.org/ministry/50/la-palabra-de-dios-para-hoy/?lang=2"));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "No se puede acceder al sitio web");
        }
    }//GEN-LAST:event_btnWebLPDDPHActionPerformed

    private void btnFolderECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderECActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirEC));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }

            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta de programa no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirEC = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnFolderECActionPerformed

    private void btnWebECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebECActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.encontacto.org/escuche"));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "No se puede acceder al sitio web");
        }
    }//GEN-LAST:event_btnWebECActionPerformed

    private void btnFolderTTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderTTBActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirTTB));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }

            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta de programa no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirTTB = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnFolderTTBActionPerformed

    private void btnWebTTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebTTBActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.twr360.org/ministry/4/a-trav-s-de-la-biblia/lang,2?gclid=EAIaIQobChMIsf338v3g7QIVGomGCh2_XwUHEAAYASAAEgJ4TPD_BwE"));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "No se puede acceder al sitio web");
        }
    }//GEN-LAST:event_btnWebTTBActionPerformed

    private void btnFolderConcienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderConcienciaActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirConciencia));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }

            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta de programa no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirConciencia = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnFolderConcienciaActionPerformed

    private void btnWebConcienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebConcienciaActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.conciencia.net/"));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "No se puede acceder al sitio web");
        }
    }//GEN-LAST:event_btnWebConcienciaActionPerformed

    private void btnFolderEALAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderEALAFActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirEALAF));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }

            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta de programa no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirEALAF = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnFolderEALAFActionPerformed

    private void btnWebEALAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebEALAFActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.enfoquealafamilia.com/programas/radio/"));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "No se puede acceder al sitio web");
        }
    }//GEN-LAST:event_btnWebEALAFActionPerformed

    private void btnEALAFMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEALAFMouseMoved
        btnEALAF.setContentAreaFilled(true);
    }//GEN-LAST:event_btnEALAFMouseMoved

    private void btnEALAFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEALAFMouseExited
        btnEALAF.setContentAreaFilled(false);
        btnEALAF.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnEALAFMouseExited

    private void btnComentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComentMouseMoved
        btnComent.setContentAreaFilled(true);
    }//GEN-LAST:event_btnComentMouseMoved

    private void btnComentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComentMouseExited
        btnComent.setContentAreaFilled(false);
        btnComent.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnComentMouseExited

    private void btnConcienciaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcienciaMouseMoved
        btnConciencia.setContentAreaFilled(true);
    }//GEN-LAST:event_btnConcienciaMouseMoved

    private void btnConcienciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcienciaMouseExited
        btnConciencia.setContentAreaFilled(false);
        btnConciencia.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnConcienciaMouseExited

    private void btnTTBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTBMouseMoved
        btnTTB.setContentAreaFilled(true);
    }//GEN-LAST:event_btnTTBMouseMoved

    private void btnTTBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTBMouseExited
        btnTTB.setContentAreaFilled(false);
        btnTTB.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnTTBMouseExited

    private void btnLPDDPHMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLPDDPHMouseMoved
        btnLPDDPH.setContentAreaFilled(true);
    }//GEN-LAST:event_btnLPDDPHMouseMoved

    private void btnLPDDPHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLPDDPHMouseExited
        btnLPDDPH.setContentAreaFilled(false);
        btnLPDDPH.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnLPDDPHMouseExited

    private void btnECMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnECMouseMoved
        btnEC.setContentAreaFilled(true);
    }//GEN-LAST:event_btnECMouseMoved

    private void btnECMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnECMouseExited
        btnEC.setContentAreaFilled(false);
        btnEC.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnECMouseExited

    private void btnRespMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRespMouseMoved
        btnResp.setContentAreaFilled(true);
    }//GEN-LAST:event_btnRespMouseMoved

    private void btnRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRespMouseExited
        btnResp.setContentAreaFilled(false);
        btnResp.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnRespMouseExited

    private void btnCruzadaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCruzadaMouseMoved
        btnCruzada.setContentAreaFilled(true);
    }//GEN-LAST:event_btnCruzadaMouseMoved

    private void btnCruzadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCruzadaMouseExited
        btnCruzada.setContentAreaFilled(false);
        btnCruzada.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnCruzadaMouseExited

    private void btnLFVPOMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLFVPOMouseMoved
        btnLFVPO.setContentAreaFilled(true);
    }//GEN-LAST:event_btnLFVPOMouseMoved

    private void btnLFVPOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLFVPOMouseExited
        btnLFVPO.setContentAreaFilled(false);
        btnLFVPO.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnLFVPOMouseExited

    private void btnEALAFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEALAFMousePressed
        ocultarBotones();
        btnFolderEALAF.setVisible(true);
        btnWebEALAF.setVisible(true);
    }//GEN-LAST:event_btnEALAFMousePressed

    private void btnComentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComentMousePressed
        ocultarBotones();
        btnFolderComent.setVisible(true);
        btnWebComent.setVisible(true);
    }//GEN-LAST:event_btnComentMousePressed

    private void btnConcienciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcienciaMousePressed
        ocultarBotones();
        btnFolderConciencia.setVisible(true);
        btnWebConciencia.setVisible(true);
    }//GEN-LAST:event_btnConcienciaMousePressed

    private void btnTTBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTBMousePressed
        ocultarBotones();
        btnFolderTTB.setVisible(true);
        btnWebTTB.setVisible(true);
    }//GEN-LAST:event_btnTTBMousePressed

    private void btnLPDDPHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLPDDPHMousePressed
        ocultarBotones();
        btnFolderLPDDPH.setVisible(true);
        btnWebLPDDPH.setVisible(true);
    }//GEN-LAST:event_btnLPDDPHMousePressed

    private void btnECMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnECMousePressed
        ocultarBotones();
        btnFolderEC.setVisible(true);
        btnWebEC.setVisible(true);
    }//GEN-LAST:event_btnECMousePressed

    private void btnRespMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRespMousePressed
        ocultarBotones();
        btnFolderResp.setVisible(true);
        btnWebResp.setVisible(true);
    }//GEN-LAST:event_btnRespMousePressed

    private void btnCruzadaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCruzadaMousePressed
        ocultarBotones();
        btnFolderCruzada.setVisible(true);
        btnWebCruzada.setVisible(true);
    }//GEN-LAST:event_btnCruzadaMousePressed

    private void btnLFVPOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLFVPOMousePressed
        ocultarBotones();
        btnFolderLFVPO.setVisible(true);
    }//GEN-LAST:event_btnLFVPOMousePressed

    private void btnWebComentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebComentActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.elsitiocristiano.com/ministries/comentarios-de-90-segundos/"));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "No se puede acceder al sitio web");
        }
    }//GEN-LAST:event_btnWebComentActionPerformed

    private void btnFolderComentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderComentActionPerformed
        Preferencias p = new Preferencias();
        p.getDirectoryPath();

        try {
            Desktop.getDesktop().open(new File(Preferencias.dirComent));
        } catch (Exception ex) {
            System.out.println(ex);

            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex1) {
                Logger.getLogger(Programas.class.getName()).log(Level.SEVERE, null, ex1);
            }

            int dialog = JOptionPane.YES_NO_OPTION;
            int warning = JOptionPane.WARNING_MESSAGE;
            int info = JOptionPane.INFORMATION_MESSAGE;
            int result = JOptionPane.showConfirmDialog(null, "Carpeta de programa no encontrada. \n ¿Buscar en carpeta?", "Error", dialog, warning);

            if (result == 0) {
                String dir = folderSelect();
                Preferencias.dirComent = dir;
                p.selectDirectoryPath();
                JOptionPane.showMessageDialog(null, "Carpeta cambiada con exito!", "Informacion", info);
                JOptionPane.showMessageDialog(null, "¡EL PROGRAMA SE REINICIARA PARA QUE FUNCIONE CORRECTAMENTE!", "AVISO!", warning);

                restartApp();
            }
        } finally {
            ocultarBarraTitulo();
        }
    }//GEN-LAST:event_btnFolderComentActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        ocultarBotones();
    }//GEN-LAST:event_jPanel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComent;
    private javax.swing.JButton btnConciencia;
    private javax.swing.JButton btnCruzada;
    private javax.swing.JButton btnEALAF;
    private javax.swing.JButton btnEC;
    private javax.swing.JButton btnFolderComent;
    private javax.swing.JButton btnFolderConciencia;
    private javax.swing.JButton btnFolderCruzada;
    private javax.swing.JButton btnFolderEALAF;
    private javax.swing.JButton btnFolderEC;
    private javax.swing.JButton btnFolderLFVPO;
    private javax.swing.JButton btnFolderLPDDPH;
    private javax.swing.JButton btnFolderResp;
    private javax.swing.JButton btnFolderTTB;
    private javax.swing.JButton btnLFVPO;
    private javax.swing.JButton btnLPDDPH;
    private javax.swing.JButton btnResp;
    private javax.swing.JButton btnTTB;
    private javax.swing.JButton btnWebComent;
    private javax.swing.JButton btnWebConciencia;
    private javax.swing.JButton btnWebCruzada;
    private javax.swing.JButton btnWebEALAF;
    private javax.swing.JButton btnWebEC;
    private javax.swing.JButton btnWebLPDDPH;
    private javax.swing.JButton btnWebResp;
    private javax.swing.JButton btnWebTTB;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
