/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alarmas;

import Frames.Principal;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;

/**
 *
 * @author Aless
 */
public class mainAlarmas extends javax.swing.JInternalFrame {
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;

    /**
     * Creates new form mainAlarmas
     */
    public mainAlarmas() throws SQLException, ClassNotFoundException {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ocultarBarraTitulo();
        menuActions();
        title();
    }
    
    public void ocultarBarraTitulo(){
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0,0);
        Barra.setPreferredSize(new Dimension(0,0));
        repaint();
    }
    
    public void menuActions(){
        setActionsAlarmas menu = new setActionsAlarmas();
        dpView.add(menu);
        menu.toFront();
        menu.setVisible(true);
    }
    
    public void title(){
        Title title = new Title();
        dpMenuAlarmas.add(title);
        title.toFront();
        title.setVisible(true);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMenuAlarmas = new javax.swing.JDesktopPane();
        dpView = new javax.swing.JDesktopPane();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dpMenuAlarmas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout dpMenuAlarmasLayout = new javax.swing.GroupLayout(dpMenuAlarmas);
        dpMenuAlarmas.setLayout(dpMenuAlarmasLayout);
        dpMenuAlarmasLayout.setHorizontalGroup(
            dpMenuAlarmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        dpMenuAlarmasLayout.setVerticalGroup(
            dpMenuAlarmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        getContentPane().add(dpMenuAlarmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1040, 310));

        dpView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout dpViewLayout = new javax.swing.GroupLayout(dpView);
        dpView.setLayout(dpViewLayout);
        dpViewLayout.setHorizontalGroup(
            dpViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        dpViewLayout.setVerticalGroup(
            dpViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        getContentPane().add(dpView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1040, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dpMenuAlarmas;
    public static javax.swing.JDesktopPane dpView;
    // End of variables declaration//GEN-END:variables
}
