package Alarmas;

import ds.desktop.notify.DesktopNotify;
import java.awt.Dimension;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Aless
 */
public class regAlarma extends javax.swing.JInternalFrame {

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;

    /**
     * Creates new form Alarmas
     */
    public regAlarma() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ocultarBarraTitulo();
        spHoraValidator();
        spMinValidator();
        lblMensaje.setVisible(false);
    }

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    public void taskProgram(int hora, int min, String msg) {
        Timer timer = new Timer();

        Calendar calendar = Calendar.getInstance();

        if (calendar.get(Calendar.HOUR_OF_DAY) > 23) {
            calendar.set(Calendar.DAY_OF_WEEK, calendar.get(Calendar.DAY_OF_WEEK) + 1);
            System.out.println(calendar.getTime() + " que pex");
        }

        calendar.set(Calendar.HOUR_OF_DAY, hora);
        calendar.set(Calendar.MINUTE, min);
        calendar.set(Calendar.SECOND, 0);
        calendar.set(Calendar.MILLISECOND, 0);

        System.out.println(calendar.getTime());

        int tiempoRepeticion = 86400000;//24h

        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                DesktopNotify.showDesktopMessage(
                        "Recordatorio",
                        msg,
                        DesktopNotify.INFORMATION);
                
                Alarma a = new Alarma();
                a.msg(msg);
                a.setVisible(true);
            }
        };

        timer.schedule(task, calendar.getTime(), tiempoRepeticion);

    }

    public void spHoraValidator() {
        SpinnerNumberModel modelo = new SpinnerNumberModel();
        modelo.setMaximum(12);
        modelo.setMinimum(0);
        spHora.setModel(modelo);

        JFormattedTextField hora = ((JSpinner.NumberEditor) spHora.getEditor()).getTextField();
        ((NumberFormatter) hora.getFormatter()).setAllowsInvalid(false);
    }

    public void spMinValidator() {
        SpinnerNumberModel modelo = new SpinnerNumberModel();
        modelo.setMaximum(59);
        modelo.setMinimum(0);
        spMin.setModel(modelo);
        JFormattedTextField minutos = ((JSpinner.NumberEditor) spMin.getEditor()).getTextField();
        ((NumberFormatter) minutos.getFormatter()).setAllowsInvalid(false);

    }

    public void setDatos() {
        String msg = txtAsunto.getText();
        Integer hora = (Integer) spHora.getValue();
        String desc = " AM";
        String and = ":";

        if (rbPM.isSelected() == true) {
            hora += 12;
            desc = " PM";
        }

        int min = (Integer) spMin.getValue();

        if (min < 10) {
            and = ":0";
        }

        taskProgram(hora, min, msg);

        JOptionPane.showMessageDialog(null, "Alarma Programada a las: " + spHora.getValue() + and + min + desc);

    }

    public void regTaskInBD() throws ClassNotFoundException, SQLException {

        Integer hora = (Integer) spHora.getValue();
        Integer min = (Integer) spMin.getValue();
        String seg = "00";

        if (rbPM.isSelected() == true) {
            hora += 12;
        }

        String hora_programado = hora + ":" + min + ":" + seg;
        String asunto = txtAsunto.getText();

        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/control_de_programas?useSSL=false", "root", "123456");
        CallableStatement stm = con.prepareCall("call sp_insertAlarmas(?,?)");

        stm.setString(1, asunto);
        stm.setString(2, hora_programado);

        stm.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbAM = new javax.swing.JRadioButton();
        rbPM = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAsunto = new javax.swing.JTextArea();
        spHora = new javax.swing.JSpinner();
        spMin = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Asunto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 70, 30));

        btnCrear.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(102, 102, 102));
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/checked.png"))); // NOI18N
        btnCrear.setText("PROGRAMAR");
        btnCrear.setContentAreaFilled(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 170, 50));

        btnCancel.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(102, 102, 102));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        btnCancel.setText("CANCELAR");
        btnCancel.setContentAreaFilled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 150, 50));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hora:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 60, 30));

        rbAM.setBackground(new java.awt.Color(255, 255, 255));
        grupo1.add(rbAM);
        rbAM.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        rbAM.setForeground(new java.awt.Color(102, 102, 102));
        rbAM.setSelected(true);
        rbAM.setText("AM");
        rbAM.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(rbAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 60, 30));

        rbPM.setBackground(new java.awt.Color(255, 255, 255));
        grupo1.add(rbPM);
        rbPM.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        rbPM.setForeground(new java.awt.Color(102, 102, 102));
        rbPM.setText("PM");
        rbPM.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(rbPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 60, 30));

        txtAsunto.setColumns(20);
        txtAsunto.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtAsunto.setForeground(new java.awt.Color(102, 102, 102));
        txtAsunto.setRows(5);
        jScrollPane1.setViewportView(txtAsunto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 330, 100));

        spHora.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jPanel1.add(spHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 60, 30));

        spMin.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jPanel1.add(spMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 60, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Minutos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 70, 30));

        lblMensaje.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 51, 51));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("msg");
        jPanel1.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 330, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1040, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String asunto = txtAsunto.getText();

        if (asunto.trim().equals("")) {
            lblMensaje.setVisible(true);
            lblMensaje.setText("LLENE LOS RECUADROS!");
            txtAsunto.requestFocus();
        } else {

            try {
                setDatos();
                regTaskInBD();

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(regAlarma.class.getName()).log(Level.SEVERE, null, ex);
            }

            setActionsAlarmas menu = new setActionsAlarmas();
            mainAlarmas.dpView.add(menu);
            menu.toFront();
            menu.setVisible(true);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        setActionsAlarmas menu = new setActionsAlarmas();
        mainAlarmas.dpView.add(menu);
        menu.toFront();
        menu.setVisible(true);

    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCrear;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JRadioButton rbAM;
    private javax.swing.JRadioButton rbPM;
    private javax.swing.JSpinner spHora;
    private javax.swing.JSpinner spMin;
    private javax.swing.JTextArea txtAsunto;
    // End of variables declaration//GEN-END:variables
}
